# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Prettier Action
      uses: creyD/prettier_action@v2.0
      #with:
        #commit_message: # optional, default is Prettified Code!
        #commit_options: # optional
        # File pattern used for "git add"
        #file_pattern: # optional, default is *
        # Options for the 'prettier' command
        #prettier_options: # optional, default is --write **/*.js
        # Branch which the changes are merged to
        #branch: 
    # Runs a set of commands using the runners shell
